import { Toaster } from "sonner";
import "./globals.css";
import { Assistant } from "next/font/google";

const assistantFont = Assistant({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "E commerce app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${assistantFont.className} antialiased`}>
        <Toaster position="top-right" />
        {children}
      </body>
    </html>
  );
}
